### ISSUE TITLE
ocrolib

### ISSUE THREAD

**Issue by KirkHadley** [sauravbiswasiupr/lstmsolver-3.0#1]
is this somehow different from ocrolib? the lstm code looks almost line for line the same

**Comment by sauravbiswasiupr** [comment]
Hi Kirk, thanks for your comments. Well my initial idea was to restructure the code from ocrolib into a proper structured format, in different classes so that you could reuse networks and trainers in a very simple fashion by importing them. Also I was looking to extend the currently existing networks and trainers and add more functionality to them. For example I had the idea of developing a 2D RNN module class that can be packaged along with the other network classes. ocrolib doesn't provide this functionality yet. It has been a really long time since I even looked into the library. But thanks a lot for your feedback. I will try to get to working on this soon and extend it per se.
